# Generated by Django 4.0.1 on 2022-01-14 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Верх', (('Худи', 'Худи'), ('bomber', 'Бомбер'))), ('Низ', (('Штаны', 'Штаны'),)), ('Обувь', (('Кроссы', 'Кроссы'), ('t', 'Туфли'))), (None, 'Неизвестно')], default=None, max_length=25)),
                ('image', models.ImageField(blank=True, upload_to='images/product/', verbose_name='Изображение')),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя покупателя')),
                ('surname', models.CharField(max_length=255, null=True, verbose_name='Фамилия покупателя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer')),
                ('products', models.ManyToManyField(blank=True, default=None, null=True, to='main.Product')),
            ],
        ),
    ]
