# Generated by Django 4.0.1 on 2022-01-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_cart_products_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Верх', (('Худи', 'Худи'), ('Бомбер', 'Бомбер'))), ('Низ', (('Штаны', 'Штаны'),)), ('Обувь', (('Кроссы', 'Кроссы'), ('Туфли', 'Туфли'))), (None, 'Неизвестно')], default=None, max_length=25),
        ),
    ]
